const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const qml=fs.readFileSync(`${__dirname}/shell.qml`,'utf8');
const Layouts=vm.createContext({});
vm.runInContext(fs.readFileSync(`${__dirname}/KeyboardLayout.js`,'utf8').replace('.pragma library',''),Layouts);
assert(Layouts.secondary,'Fn action map must exist');
const sent=[];
const ctx=vm.createContext({Layouts,fn:false,fnLocked:false,held:{},used:{},shift:false,control:false,alt:false,logo:false,
 russian:true,autocorrectEnabled:false,predictionEnabled:false,padEnabled:true,settingsOpen:false,themeName:"system",drag:false,
 pad:{stopMomentum(){},resetGesture(){}},clearWord(){},updateWord(){},lastTypedAt:0,send:e=>sent.push(e),toggleOverview(){this.overviewOpened=true}});
Object.defineProperty(ctx,'fnActive',{get(){return ctx.fn!==ctx.fnLocked;}});
vm.runInContext(qml.slice(qml.indexOf('    function runAction('),qml.indexOf('    function click(button)')),ctx);
const keyEvents=()=>sent.filter(e=>e.type==='key'||e.type==='text'||e.type==='action');
ctx.typeKey('F1');assert.equal(keyEvents().at(-1).key,'F1');
ctx.fn=true;ctx.typeKey('F1');assert.equal(keyEvents().at(-1).action,'mute');assert.equal(ctx.fn,false);
ctx.fn=true;ctx.holdMod('fn',true);
ctx.typeKey('F2');ctx.typeKey('F3');assert.equal(ctx.fn,true);assert.equal(keyEvents().at(-1).action,'volume-up');
ctx.holdMod('fn',false);assert.equal(ctx.fn,false);
ctx.fn=true;ctx.typeKey('Escape');assert.equal(ctx.fnLocked,true);assert.equal(ctx.fnActive,true);
ctx.typeKey('F4');assert.equal(keyEvents().at(-1).action,'mic-mute');
ctx.fn=true;ctx.typeKey('F4');assert.equal(keyEvents().at(-1).key,'F4');assert.equal(ctx.fnActive,true);
ctx.typeKey('Escape');assert.equal(ctx.fnLocked,true);assert.equal(keyEvents().at(-1).key,'Escape');
ctx.fn=true;ctx.typeKey('Escape');assert.equal(ctx.fnLocked,false);
ctx.alt=true;ctx.typeKey('F4');assert.equal(keyEvents().at(-1).key,'F4');assert.deepEqual(Array.from(keyEvents().at(-1).mods),['alt']);
ctx.fn=true;ctx.control=true;ctx.typeKey('Left');assert.equal(keyEvents().at(-1).key,'Home');assert.deepEqual(Array.from(keyEvents().at(-1).mods),['ctrl']);
ctx.fn=true;ctx.typeKey('Up');assert.equal(keyEvents().at(-1).key,'Prior');
ctx.fn=true;ctx.typeKey('Down');assert.equal(keyEvents().at(-1).key,'Next');
ctx.fn=true;ctx.typeText(' ');assert.equal(ctx.themeName,'oled-black');
ctx.fn=true;ctx.typeText('\\');assert.equal(keyEvents().at(-1).action,'audio');
ctx.fn=true;ctx.typeText('q');assert.equal(keyEvents().at(-1).text,'q');assert.equal(ctx.fn,false);
ctx.fn=true;ctx.typeKey('F10');assert.equal(ctx.padEnabled,false);
ctx.fn=true;ctx.typeKey('F10');assert.equal(ctx.padEnabled,true);
ctx.fn=true;ctx.typeKey('F11');assert.equal(ctx.predictionEnabled,true);
ctx.fn=true;ctx.typeKey('F12');assert.equal(ctx.settingsOpen,true);
console.log('PASS: F keys, one-shot/held Fn, FnLock/inversion, Alt+F4, Ctrl+Home, page keys, local actions and text fallback');
